/*
 * Wikimedia REST API
 *
 * This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats. ### Global Rules - Limit your clients to no more than 200 requests/s to this API.   Each API endpoint's documentation may detail more specific usage limits. - Set a unique `User-Agent` or `Api-User-Agent` header that   allows us to contact you quickly. Email addresses or URLs   of contact pages work well.  By using this API, you agree to Wikimedia's [Terms of Use](https://wikimediafoundation.org/wiki/Terms_of_Use) and [Privacy Policy](https://wikimediafoundation.org/wiki/Privacy_policy). Unless otherwise specified in the endpoint documentation below, content accessed via this API is licensed under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) and [GFDL](https://www.gnu.org/copyleft/fdl.html) licenses, and you irrevocably agree to release modifications or additions made through this API under these licenses. See https://www.mediawiki.org/wiki/REST_API for background and details. ### Endpoint documentation Please consult each endpoint's documentation for details on: - Licensing information for the specific type of content   and data served via the endpoint. - Stability markers to inform you about development status and   change policy, according to   [our API version policy](https://www.mediawiki.org/wiki/API_versioning). - Endpoint specific usage limits. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Announcement struct {
	// Unique ID of the announcement
	Id string `json:"id"`
	// The type of announcement. Possible values are \"survey\" or \"fundraising\"
	Type_ string `json:"type"`
	// The date to begin showing the announcement
	StartTime string `json:"start_time"`
	// The date to stop showing the announcement
	EndTime string `json:"end_time"`
	// An array of platforms to display the announcement. Possible values are \"iOSApp\" or \"AndroidApp\"
	Platforms []string `json:"platforms"`
	// The text of the announcement
	Text string `json:"text"`
	// The URL of the image for the announcement
	Image string `json:"image,omitempty"`
	Action *Action `json:"action,omitempty"`
	// HTML to display below the announcement. Usually a privacy statment and link to a policy
	CaptionHTML string `json:"caption_HTML,omitempty"`
	// An array of country codes in which to display the announcement. Clients should derive the country from 'GeoIP' portion of the Set-Cookie header 
	Countries []string `json:"countries"`
}
