/*
 * Wikimedia REST API
 *
 * This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats. ### Global Rules - Limit your clients to no more than 200 requests/s to this API.   Each API endpoint's documentation may detail more specific usage limits. - Set a unique `User-Agent` or `Api-User-Agent` header that   allows us to contact you quickly. Email addresses or URLs   of contact pages work well.  By using this API, you agree to Wikimedia's [Terms of Use](https://wikimediafoundation.org/wiki/Terms_of_Use) and [Privacy Policy](https://wikimediafoundation.org/wiki/Privacy_policy). Unless otherwise specified in the endpoint documentation below, content accessed via this API is licensed under the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) and [GFDL](https://www.gnu.org/copyleft/fdl.html) licenses, and you irrevocably agree to release modifications or additions made through this API under these licenses. See https://www.mediawiki.org/wiki/REST_API for background and details. ### Endpoint documentation Please consult each endpoint's documentation for details on: - Licensing information for the specific type of content   and data served via the endpoint. - Stability markers to inform you about development status and   change policy, according to   [our API version policy](https://www.mediawiki.org/wiki/API_versioning). - Endpoint specific usage limits. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Summary struct {
	Titles *TitlesSet `json:"titles"`
	// The page title. Deprecated: Use `titles.normalized` instead. 
	Title string `json:"title,omitempty"`
	// The page title how it should be shown to the user. Deprecated: Use `titles.display` instead. 
	Displaytitle string `json:"displaytitle,omitempty"`
	// The page ID
	Pageid int32 `json:"pageid,omitempty"`
	// First several sentences of an article in plain text
	Extract string `json:"extract"`
	// First several sentences of an article in simple HTML format
	ExtractHtml string `json:"extract_html,omitempty"`
	Thumbnail *Thumbnail `json:"thumbnail,omitempty"`
	Originalimage *Originalimage `json:"originalimage,omitempty"`
	// The page language code
	Lang string `json:"lang"`
	// The page language direction code
	Dir string `json:"dir"`
	// The time when the page was last edited in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format
	Timestamp string `json:"timestamp,omitempty"`
	// Wikidata description for the page
	Description string `json:"description,omitempty"`
	Coordinates *SummaryCoordinates `json:"coordinates,omitempty"`
}
